### ISSUE TITLE
EMFJson does not support EDataType that are arrays anymore

### ISSUE THREAD

**Issue by axtmann** [emfjson/emfjson-jackson#100]
If you have an EDataType with Instance Class Name **java.lang.Object[]** (An array of objects) the version 1.0.* does not support de-serializing anymore and end with the exception below.

The problem doesn't exist in version 0.15. In version 0.15, org.emfjson.jackson.databind.deser.EObjectDeserializer uses the instance class (line 388). Obviously this does not happen anymore. 

`com.fasterxml.jackson.databind.JsonMappingException: Invalid hexadecimal (through reference chain: org.eclipse.emf.ecore.util.EDataTypeUniqueEList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:189)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:266)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at org.emfjson.jackson.databind.property.EObjectFeatureProperty.deserializeAndSet(EObjectFeatureProperty.java:63)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.postDeserialize(EObjectDeserializer.java:154)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:92)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:38)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:75)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:30)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1513)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
	at org.emfjson.jackson.resource.JsonResource.doLoad(JsonResource.java:191)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
...
Caused by: java.lang.NumberFormatException: Invalid hexadecimal
	at org.eclipse.emf.ecore.impl.EFactoryImpl.hexCharToByte(EFactoryImpl.java:619)
	at org.eclipse.emf.ecore.impl.EFactoryImpl.hexStringToBytes(EFactoryImpl.java:570)
	at org.eclipse.emf.ecore.impl.EFactoryImpl.createFromString(EFactoryImpl.java:655)
	at com.swarco.gecko.impl.GeckoFactoryImpl.createObjectArrayFromString(GeckoFactoryImpl.java:299)
	at com.swarco.gecko.impl.GeckoFactoryImpl.createFromString(GeckoFactoryImpl.java:92)
	at org.eclipse.emf.ecore.util.EcoreUtil.createFromString(EcoreUtil.java:3681)
	at org.emfjson.jackson.databind.deser.EDataTypeDeserializer.deserialize(EDataTypeDeserializer.java:32)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	... 39 more`

**Comment by axtmann** [comment]
This is the ecore excerpt:
`
  <eClassifiers xsi:type="ecore:EClass" name="TestObject">
     <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" upperBound="-1" eType="#//ObjectArray">
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ObjectArray" instanceClassName="java.lang.Object[]">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A special DataType to handle two-dimensional arrays in JSON"/>
    </eAnnotations>
  </eClassifiers>
`

This is the JSON Example
`{ ...
    "data": [
        [201707250000, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        [201707250100, 1, 0, 0, 74, 0, 13, 0, 0, 0, 2, 0, 116, 88, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [201707260000]
    ]
... }
`

I know, its not  the way of modeling, but the JSON data come from an embedded device ;-)

**Comment by ghillairet** [comment]
@axtmann Should be fixed in https://github.com/emfjson/emfjson-jackson/commit/4ce4430dbdfa854809b027e4066c306b33f7fa71
